
services:
  mysql:
    image: mysql:8.0
    container_name: nuxt-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nuxtapp
      MYSQL_USER: nuxtuser
      MYSQL_PASSWORD: nuxtpass
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  nuxt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nuxt-app
    ports:
      - "3000:3000"
    volumes:
      - ./nuxt:/app
    working_dir: /app
    command: "pnpm dev"
    depends_on:
      - mysql

volumes:
  db-data: